import org.apache.hadoop.fs.impl.WrappedIOException;
public class FunctionUse4262 {
public void funcUse() {
WrappedIOException wrappedioexception = new WrappedIOException();
wrappedioexception.getCause();
}
}